### ISSUE TITLE
Proper error numbers

### ISSUE THREAD

**Issue by marblekettle** [NEKuipers/minishell#6]
<$ mkdir noperm
<$ chmod 000 noperm
<$ cd noperm
Should produce:
bash: cd: noperm: Permission denied
Produces:
minishell: cd: noperm: No such file or directory

Unclear whether this is required by subject, but seems possible given the inclusion of strerror and perror

**Comment by NEKuipers** [comment]
Annoyingly, chdir returns -1 upon failure regardless of the reason, so couldn't use this to solve the problem. Using the system call access(directory, R_OK) sets errno to 13 (permission denied) which allowed me to make a different error message.

Issue resolved.
