### ISSUE TITLE
Exit not recognized as builtin sometimes

### ISSUE THREAD

**Issue by marblekettle** [NEKuipers/minishell#8]
$> exit 1 | exit 2 | exit 3
Produces:
minishell: exit: command not found
minishell: exit: command not found

Issue not present in bmans_2, so recently introduced

**Comment by NEKuipers** [comment]
currently looking into this. The issue here isn't really the executing. It enters shell_exit the appropriate amount of times and has the correct return value. It just shouldn't print the minishell:exit:cmd not found

**Comment by NEKuipers** [comment]
Just figured out this issue was always already there, it's just only now showing up because we changed the minishell:command not found message to write to STDERR lol

**Comment by NEKuipers** [comment]
The following if statement works as a quick fix
			
			if (ft_strcmp(args[0], "exit") != 0)
				ft_printf_fd(STDERR, "minishell: %s: command not found\n", args[0]);

**Comment by NEKuipers** [comment]
Added the above statement, had to rewrite some stuff to fix it to norme. I tested exit for a little while, think we're good here. Closing this issue.
